Repository eurofurence/ef-app_backend-dotnet-core, pull requests merged in 2024-08, with the labels that each got.

#140 137 fix soft delete
  src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
  src/Eurofurence.App.Infrastructure.EntityFramework/AppDbContext.cs
Labels: bug

#141 fix: use jsonignore attribute instead of response classes
  Dockerfile
  Dockerfile-backoffice
  src/Eurofurence.App.Backoffice/Components/ImageDialog.razor
  src/Eurofurence.App.Backoffice/Services/ArtistAlleyService.cs
  src/Eurofurence.App.Backoffice/Services/FursuitService.cs
  src/Eurofurence.App.Backoffice/Services/IArtistAlleyService.cs
  src/Eurofurence.App.Backoffice/Services/IFursuitService.cs
  src/Eurofurence.App.Backoffice/Services/IImageService.cs
  src/Eurofurence.App.Backoffice/Services/ImageService.cs
  src/Eurofurence.App.Domain.Model/Announcements/AnnouncementRecord.cs
  src/Eurofurence.App.Domain.Model/ArtistsAlley/TableRegistrationRecord.cs
  src/Eurofurence.App.Domain.Model/ArtistsAlley/TableRegistrationResponse.cs
  src/Eurofurence.App.Domain.Model/Dealers/DealerRecord.cs
  src/Eurofurence.App.Domain.Model/Dealers/DealerRequest.cs
  src/Eurofurence.App.Domain.Model/EntityBase.cs
  src/Eurofurence.App.Domain.Model/Events/EventConferenceDayRecord.cs
  src/Eurofurence.App.Domain.Model/Events/EventConferenceRoomRecord.cs
  src/Eurofurence.App.Domain.Model/Events/EventConferenceTrackRecord.cs
  src/Eurofurence.App.Domain.Model/Events/EventRecord.cs
  src/Eurofurence.App.Domain.Model/Fursuits/CollectingGame/FursuitParticipationRecord.cs
  src/Eurofurence.App.Domain.Model/Fursuits/FursuitBadgeRecord.cs
  src/Eurofurence.App.Domain.Model/Fursuits/FursuitBadgeResponse.cs
  src/Eurofurence.App.Domain.Model/Fursuits/FursuitParticipationInfoResponse.cs
  src/Eurofurence.App.Domain.Model/Images/ImageRecord.cs
  src/Eurofurence.App.Domain.Model/Images/ImageResponse.cs
  src/Eurofurence.App.Domain.Model/Images/ImageWithRelationsResponse.cs
  src/Eurofurence.App.Domain.Model/Knowledge/KnowledgeEntryRecord.cs
  src/Eurofurence.App.Domain.Model/Maps/MapEntryRecord.cs
  src/Eurofurence.App.Domain.Model/Maps/MapEntryRequest.cs
  src/Eurofurence.App.Domain.Model/Maps/MapEntryResponse.cs
  src/Eurofurence.App.Domain.Model/Maps/MapRecord.cs
  src/Eurofurence.App.Domain.Model/Maps/MapRequest.cs
  src/Eurofurence.App.Domain.Model/Maps/MapResponse.cs
  src/Eurofurence.App.Domain.Model/Storage/AggregatedDeltaResponse.cs
  src/Eurofurence.App.Infrastructure.EntityFramework/Migrations/AppDbContextModelSnapshot.cs
  src/Eurofurence.App.Server.Services/Abstractions/MinIO/MinIOConfiguration.cs
  src/Eurofurence.App.Server.Services/Dealers/DealerService.cs
  src/Eurofurence.App.Server.Services/EntityServiceBase.cs
  src/Eurofurence.App.Server.Services/Events/EventService.cs
  src/Eurofurence.App.Server.Services/Images/ImageService.cs
  src/Eurofurence.App.Server.Services/Knowledge/KnowledgeEntryService.cs
  src/Eurofurence.App.Server.Services/Maps/MapService.cs
  src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
  src/Eurofurence.App.Server.Web/Controllers/DealersController.cs
  src/Eurofurence.App.Server.Web/Controllers/FursuitsController.cs
  src/Eurofurence.App.Server.Web/Controllers/ImagesController.cs
  src/Eurofurence.App.Server.Web/Controllers/MapsController.cs
  src/Eurofurence.App.Server.Web/Controllers/SyncController.cs
Labels: bug

#145 feat(rbac): rework access roles
  src/Eurofurence.App.Server.Services/Abstractions/ArtistsAlley/ITableRegistrationService.cs
  src/Eurofurence.App.Server.Services/ArtistsAlley/TableRegistrationService.cs
  src/Eurofurence.App.Server.Web/Controllers/AnnouncementsController.cs
  src/Eurofurence.App.Server.Web/Controllers/ArtShowController.cs
  src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
  src/Eurofurence.App.Server.Web/Controllers/CommunicationController.cs
  src/Eurofurence.App.Server.Web/Controllers/DealersController.cs
  src/Eurofurence.App.Server.Web/Controllers/EventFeedbackController.cs
  src/Eurofurence.App.Server.Web/Controllers/FursuitsController.cs
  src/Eurofurence.App.Server.Web/Controllers/ImagesController.cs
  src/Eurofurence.App.Server.Web/Controllers/KnowledgeEntriesController.cs
  src/Eurofurence.App.Server.Web/Controllers/KnowledgeGroupsController.cs
  src/Eurofurence.App.Server.Web/Controllers/MapsController.cs
  src/Eurofurence.App.Server.Web/Controllers/PushNotificationsController.cs
  src/Eurofurence.App.Server.Web/Identity/AuthorizationOptions.cs
  src/Eurofurence.App.Server.Web/Identity/RolesClaimsTransformation.cs
  src/Eurofurence.App.Server.Web/appsettings.sample.json
Labels: enhancement

#153 feat(preview): support /Web/Events route
  src/Eurofurence.App.Server.Services/Abstractions/ConventionSettings.cs
  src/Eurofurence.App.Server.Web/Controllers/EventsController.cs
  src/Eurofurence.App.Server.Web/Controllers/WebPreviewController.cs
  src/Eurofurence.App.Server.Web/Views/WebPreview/DealerPreview.cshtml
  src/Eurofurence.App.Server.Web/Views/WebPreview/EventPreview.cshtml
  src/Eurofurence.App.Server.Web/Views/WebPreview/EventsPreview.cshtml
  src/Eurofurence.App.Server.Web/Views/WebPreview/KnowledgeEntryPreview.cshtml
Labels: enhancement

#158 feat(backoffice): require authorization for pages
  src/Eurofurence.App.Backoffice/App.razor
  src/Eurofurence.App.Backoffice/Authentication/AuthorizationSettings.cs
  src/Eurofurence.App.Backoffice/Authentication/BackendAccountClaimsFactory.cs
  src/Eurofurence.App.Backoffice/Layout/NavMenu.razor
  src/Eurofurence.App.Backoffice/Pages/DebugClaims.razor
  src/Eurofurence.App.Backoffice/Pages/Home.razor
  src/Eurofurence.App.Backoffice/Pages/Images.razor
  src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
  src/Eurofurence.App.Backoffice/Program.cs
  src/Eurofurence.App.Backoffice/Services/IUsersService.cs
  src/Eurofurence.App.Backoffice/Services/UsersService.cs
  src/Eurofurence.App.Backoffice/wwwroot/appsettings.sample.json
  src/Eurofurence.App.Backoffice/wwwroot/index.html
  src/Eurofurence.App.Domain.Model/Users/UserRecord.cs
  src/Eurofurence.App.Domain.Model/Users/UserRegistration.cs
  src/Eurofurence.App.Domain.Model/Users/UserRegistrationClaims.cs
  src/Eurofurence.App.Domain.Model/Users/UserRegistrationStatus.cs
  src/Eurofurence.App.Server.Web/Controllers/UsersController.cs
  src/Eurofurence.App.Server.Web/Identity/AuthorizationOptions.cs
  src/Eurofurence.App.Server.Web/Identity/RolesClaimsTransformation.cs
Labels: enhancement

#161 feat(artistalley): submit/delete image with registration
  Dockerfile
  Dockerfile-backoffice
  justfile
  scripts/import.py
  src/Eurofurence.App.Domain.Model/ArtistsAlley/TableRegistrationRecord.cs
  src/Eurofurence.App.Domain.Model/ArtistsAlley/TableRegistrationRequest.cs
  src/Eurofurence.App.Infrastructure.EntityFramework/AppDbContext.cs
  src/Eurofurence.App.Server.Services/Abstractions/ArtistsAlley/ITableRegistrationService.cs
  src/Eurofurence.App.Server.Services/Abstractions/Images/IImageService.cs
  src/Eurofurence.App.Server.Services/ArtistsAlley/TableRegistrationService.cs
  src/Eurofurence.App.Server.Services/Dealers/DealerService.cs
  src/Eurofurence.App.Server.Services/Events/EventService.cs
  src/Eurofurence.App.Server.Services/Images/ImageService.cs
  src/Eurofurence.App.Server.Services/LostAndFound/LostAndFoundLassieImporter.cs
  src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
  src/Eurofurence.App.Server.Web/Jobs/FlushPrivateMessageNotificationsJob.cs
  src/Eurofurence.App.Server.Web/Jobs/UpdateAnnouncementsJob.cs
  src/Eurofurence.App.Server.Web/Jobs/UpdateDealersJob.cs
  src/Eurofurence.App.Server.Web/Jobs/UpdateEventsJob.cs
  src/Eurofurence.App.Server.Web/Jobs/UpdateFursuitCollectionGameParticipationJob.cs
  src/Eurofurence.App.Server.Web/Jobs/UpdateLostAndFoundJob.cs
Labels: bug, enhancement

#162 feat: input validation for user input
  src/Eurofurence.App.Server.Services/Abstractions/Sanitization/IHtmlSanitizer.cs
  src/Eurofurence.App.Server.Services/Abstractions/Sanitization/IHttpUriSanitizer.cs
  src/Eurofurence.App.Server.Services/ArtistsAlley/TableRegistrationService.cs
  src/Eurofurence.App.Server.Services/Dealers/DealerService.cs
  src/Eurofurence.App.Server.Services/DependencyResolution/AutofacModule.cs
  src/Eurofurence.App.Server.Services/Eurofurence.App.Server.Services.csproj
  src/Eurofurence.App.Server.Services/Knowledge/KnowledgeEntryService.cs
  src/Eurofurence.App.Server.Services/Sanitization/HtmlSanitizer.cs
  src/Eurofurence.App.Server.Services/Sanitization/HttpUriSanitizer.cs
  src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
Labels: enhancement

#173 feat: sanitize inputs and replace Markdown editor
  src/Eurofurence.App.Backoffice/Components/ImageDialog.razor
  src/Eurofurence.App.Backoffice/Components/KnowledgeEntryDialog.razor
  src/Eurofurence.App.Backoffice/Components/KnowledgeGroupDialog.razor
  src/Eurofurence.App.Backoffice/Components/LinkFragmentDialog.razor
  src/Eurofurence.App.Backoffice/Components/TinyMarkdownEditor.cs
  src/Eurofurence.App.Backoffice/Components/TinyMarkdownEditor.razor
  src/Eurofurence.App.Backoffice/Components/TinyMarkdownEditor.razor.js
  src/Eurofurence.App.Backoffice/Eurofurence.App.Backoffice.csproj
  src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
  src/Eurofurence.App.Backoffice/_Imports.razor
  src/Eurofurence.App.Backoffice/wwwroot/css/tiny-mde.min.css
  src/Eurofurence.App.Backoffice/wwwroot/index.html
  src/Eurofurence.App.Backoffice/wwwroot/scripts/tiny-mde.min.js
  test/Eurofurence.App.Server.Services.Tests/Eurofurence.App.Server.Services.Tests.csproj
Labels: enhancement

#174 fix(backoffice): markdown and kb styling
  .gitignore
  src/Eurofurence.App.Backoffice/Components/MarkdownRenderer.razor
  src/Eurofurence.App.Backoffice/Components/MarkdownRenderer.razor.css
  src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
Labels: enhancement

#175 168 fix entities being listed as changed due to import
  src/Eurofurence.App.Backoffice/Authentication/BackendAccountClaimsFactory.cs
  src/Eurofurence.App.Backoffice/Authentication/TokenAuthorizationMessageHandler.cs
  src/Eurofurence.App.Backoffice/Layout/RedirectToLogin.razor
  src/Eurofurence.App.Backoffice/Program.cs
  src/Eurofurence.App.Backoffice/Services/IUserService.cs
  src/Eurofurence.App.Backoffice/Services/UserService.cs
  src/Eurofurence.App.Backoffice/wwwroot/index.html
  src/Eurofurence.App.Common/DataDiffUtils/PatchDefinition.cs
Labels: bug

#191 fix(pm): fix crash when reading private messages
  src/Eurofurence.App.Server.Services/Communication/PrivateMessageService.cs
  src/Eurofurence.App.Server.Web/Identity/RolesClaimsTransformation.cs
Labels: bug

#188 feat!: Removed previously deprecated image content endpoints
  src/Eurofurence.App.Server.Web/Controllers/ImagesController.cs
Labels: feature
