Repository eurofurence/ef-app_backend-dotnet-core, pull requests merged in 2024-09, with the labels that each got.

#206 fix(logging): reduce logging for requests
  src/Eurofurence.App.Server.Web/Controllers/DealersController.cs
  src/Eurofurence.App.Server.Web/Eurofurence.App.Server.Web.csproj
  src/Eurofurence.App.Server.Web/Startup.cs
  src/Eurofurence.App.Server.Web/appsettings.sample.json
Labels: enhancement

#207 fix: Made web external links clickable
  src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
Labels: bug, enhancement

#208 feat: Added web preview link for knowledge base entries and groups
  justfile
  src/Eurofurence.App.Backoffice/Pages/KnowledgeBase.razor
  src/Eurofurence.App.Backoffice/Program.cs
  src/Eurofurence.App.Backoffice/wwwroot/appsettings.sample.json
Labels: feature

#213 feat: Made links editable
  src/Eurofurence.App.Backoffice/Components/KnowledgeEntryDialog.razor
  src/Eurofurence.App.Backoffice/Components/LinkFragmentDialog.razor
Labels: bug, feature

#215 feat: delete aleady aproved/rejected artist alley applications
  src/Eurofurence.App.Backoffice/Components/ArtistAlleyApplicationDialog.razor
  src/Eurofurence.App.Backoffice/Pages/ArtistAlleyModeration.razor
  src/Eurofurence.App.Server.Web/Controllers/ArtistsAlleyController.cs
Labels: bug, feature
